### ISSUE TITLE
TypeError: Cannot read property 'compile' of undefined on Windows10

### ISSUE THREAD

**Issue by steermomo** [luuman/hexo-theme-spfk#11]
When I use `hexo -g`

```
INFO  Start processing
ERROR Process failed: layout/archive.ejs
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (C:\Users\lomom\Documents\GitHub\blog\node_modules\hexo\lib\theme\view.js:104:22)
    at View (C:\Users\lomom\Documents\GitHub\blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (C:\Users\lomom\Documents\GitHub\blog\node_modules\hexo\lib\theme\index.js:37:10)
    ...
INFO  Files loaded in 4.31 s

WARN  No layout: about/index.html
WARN  No layout: 2016/03/13/queue-i/index.html
...
INFO  Generated: background/bg-21.jpg
INFO  Generated: background/bg-16.jpg
INFO  140 files generated in 2.8 s
```

but when use `landscape` no error happens.

那么问题来了，这是主题的问题还是hexo的问题呢

**Comment by steermomo** [comment]
After reinstall node.js and hexo,everything is OK.
