### ISSUE TITLE
generate出错

### ISSUE THREAD

**Issue by iMissWonder** [luuman/hexo-theme-spfk#19]
但是可以用hexo s -g在本地查看，不知道为什么，错误信息如下，求助呀！

```
$ hexo g
INFO  Start processing
INFO  Files loaded in 307 ms
Unhandled rejection TypeError: D:\Cloud\Web\Hexo\themes\spfk\layout\post.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>
    2|

D:\Cloud\Web\Hexo\themes\spfk\layout\_partial\article.ejs:91
    89| <% } %>
    90|
 >> 91| <%- partial('_partial/post-nav-button') %>
    92|
    93| <% if (!index) { %>
    94|     <script>

D:\Cloud\Web\Hexo\themes\spfk\layout\_partial\post-nav-button.ejs:16
    14|             </a>
    15|         <% } else { %>
 >> 16|             <a href="<%- url_for(post.next.path) %>" title="下一篇: <%= post.next.title %>">
    17|                 <i class="fa fa-angle-right"></i>
    18|             </a>
    19|         <% } %>

Cannot read property 'path' of undefined
    at eval (eval at <anonymous> (D:\Cloud\Web\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:1014)
    at eval (eval at <anonymous> (D:\Cloud\Web\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2194)
    at null._compiledSync (D:\Cloud\Web\Hexo\node_modules\ejs\lib\ejs.js:255:15)
    at View.renderSync (D:\Cloud\Web\Hexo\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Cloud\Web\Hexo\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Cloud\Web\Hexo\node_modules\lodash\lodash.js:4167:19)
    at eval (eval at <anonymous> (D:\Cloud\Web\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:38:126)
    at eval (eval at <anonymous> (D:\Cloud\Web\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:38:454)
    at null._compiledSync (D:\Cloud\Web\Hexo\node_modules\ejs\lib\ejs.js:255:15)
    at View.renderSync (D:\Cloud\Web\Hexo\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Cloud\Web\Hexo\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Cloud\Web\Hexo\node_modules\lodash\lodash.js:4167:19)
    at eval (eval at <anonymous> (D:\Cloud\Web\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (D:\Cloud\Web\Hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:103)
    at null._compiledSync (D:\Cloud\Web\Hexo\node_modules\ejs\lib\ejs.js:255:15)
    at tryCatcher (D:\Cloud\Web\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at null._compiled (D:\Cloud\Web\Hexo\node_modules\bluebird\js\release\method.js:15:34)
    at View.render (D:\Cloud\Web\Hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Cloud\Web\Hexo\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (D:\Cloud\Web\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Cloud\Web\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Cloud\Web\Hexo\node_modules\hexo\lib\hexo\router.js:134:3)
INFO  Generated: 2016/04/13/corcpp/index.html
INFO  Generated: 2016/03/20/dream/index.html
INFO  Generated: 2016/03/19/markdown/index.html
```

**Comment by luuman** [comment]
https://github.com/luuman/hexo-theme-spfk/commit/8b4bd88ea7710c74dd02a240a8d6cbc84360d8fe

修改
